//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "AGG_GROUP")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub agg_group_seq: i64,
    pub agg_group_name: String,
    pub is_active: bool,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub created_by: String,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::telegram_room::Entity")]
    TelegramRoom,
}

impl Related<super::telegram_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TelegramRoom.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
