//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "COMMON_CONSUME_KEYWORD_TYPE")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub consume_keyword_type_id: i64,
    #[sea_orm(unique)]
    pub consume_keyword_type: String,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub created_by: String,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::common_consume_prodt_keyword::Entity")]
    CommonConsumeProdtKeyword,
}

impl Related<super::common_consume_prodt_keyword::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommonConsumeProdtKeyword.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
