//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "COMMON_CONSUME_PRODT_KEYWORD")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub consume_keyword_id: i64,
    #[sea_orm(unique)]
    pub consume_keyword: String,
    pub keyword_weight: i32,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub created_by: String,
    pub updated_by: Option<String>,
    pub consume_keyword_type_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::common_consume_keyword_type::Entity",
        from = "Column::ConsumeKeywordTypeId",
        to = "super::common_consume_keyword_type::Column::ConsumeKeywordTypeId"
    )]
    CommonConsumeKeywordType,
    #[sea_orm(has_many = "super::spent_detail::Entity")]
    SpentDetail,
}

impl Related<super::common_consume_keyword_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommonConsumeKeywordType.def()
    }
}

impl Related<super::spent_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpentDetail.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
