//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "DEPOSIT_ASSET")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub deposit_seq: i64,
    pub deposit_name: String,
    pub deposit_amount: Decimal,
    pub interest_rate: Decimal,
    pub deposit_start_date: DateTime,
    pub deposit_end_date: DateTime,
    pub user_seq: i64,
    pub currency_code: String,
    pub is_terminated: bool,
    pub term_month: i32,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub created_by: String,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserSeq",
        to = "super::users::Column::UserSeq"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::currency_code::Entity",
        from = "Column::CurrencyCode",
        to = "super::currency_code::Column::CurrencyCode"
    )]
    CurrencyCode,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::currency_code::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CurrencyCode.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
