//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "DIM_CALENDAR")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub dt: Date,
    pub yyyy: i16,
    pub mm: i8,
    pub dd: i8,
    pub yyyymm: String,
    pub yyyymmdd: String,
    pub day_of_month: i8,
    pub quarter_no: i8,
    pub half_no: i8,
    pub weekday_no: i8,
    pub is_weekend: i8,
    pub is_weekday: i8,
    pub is_month_start: i8,
    pub is_month_end: i8,
    pub remaining_days_in_month: i8,
    pub is_holiday: i8,
    pub is_before_holiday: i8,
    pub is_after_holiday: i8,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub created_by: String,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
