//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "EARNED_DETAIL")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub earned_idx: i64,
    pub earned_name: String,
    pub earned_money: i64,
    pub earned_money_dollor: Decimal,
    pub earned_at: DateTime,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub created_by: String,
    pub updated_by: Option<String>,
    pub user_seq: i64,
    pub room_seq: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserSeq",
        to = "super::users::Column::UserSeq"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::telegram_room::Entity",
        from = "Column::RoomSeq",
        to = "super::telegram_room::Column::RoomSeq"
    )]
    TelegramRoom,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::telegram_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TelegramRoom.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
