//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod agg_group;
pub mod common_consume_keyword_type;
pub mod common_consume_prodt_keyword;
pub mod dim_calendar;
pub mod spent_detail;
pub mod spent_detail_indexing;
pub mod spent_group_info;
pub mod telegram_room;
pub mod user_payment_methods;
pub mod users;
