//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::consume_prodt_detail::Entity as ConsumeProdtDetail;
pub use super::consume_prodt_detail_backupver::Entity as ConsumeProdtDetailBackupver;
pub use super::consume_prodt_keyword::Entity as ConsumeProdtKeyword;
pub use super::consumue_keyword_type::Entity as ConsumueKeywordType;
pub use super::users::Entity as Users;
