//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::common_consume_keyword_type::Entity as CommonConsumeKeywordType;
pub use super::common_consume_prodt_keyword::Entity as CommonConsumeProdtKeyword;
pub use super::consume_prodt_detail::Entity as ConsumeProdtDetail;
pub use super::consume_prodt_keyword::Entity as ConsumeProdtKeyword;
pub use super::consumue_keyword_type::Entity as ConsumueKeywordType;
pub use super::spent_detail::Entity as SpentDetail;
pub use super::spent_group_info::Entity as SpentGroupInfo;
pub use super::telegram_room::Entity as TelegramRoom;
pub use super::users::Entity as Users;
