//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "SPENT_GROUP_INFO")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub spent_group_id: i64,
    #[sea_orm(unique)]
    pub spent_group_nm: Option<String>,
    pub status: Option<String>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub created_by: String,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::spent_detail::Entity")]
    SpentDetail,
}

impl Related<super::spent_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpentDetail.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
