//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "SPENT_DETAIL_INDEXING")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub spent_idx: i64,
    pub spent_name: String,
    pub spent_money: i64,
    pub spent_at: DateTime,
    pub created_at: DateTime,
    pub user_seq: i64,
    pub consume_keyword_type_id: i64,
    pub consume_keyword_type: String,
    pub room_seq: i64,
    pub user_id: String,
    pub card_alias: String,
    pub updated_at: Option<DateTime>,
    pub updated_by: Option<String>,
    pub agg_group_seq: i64
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
