//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "SPENT_DETAIL")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub spent_idx: i64,
    pub spent_name: String,
    pub spent_money: i32,
    pub spent_at: DateTime,
    pub should_index: i8,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub created_by: String,
    pub updated_by: Option<String>,
    pub user_seq: i64,
    pub spent_group_id: i64,
    pub consume_keyword_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::spent_group_info::Entity",
        from = "Column::SpentGroupId",
        to = "super::spent_group_info::Column::SpentGroupId"
    )]
    SpentGroupInfo,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserSeq",
        to = "super::users::Column::UserSeq"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::common_consume_prodt_keyword::Entity",
        from = "Column::ConsumeKeywordId",
        to = "super::common_consume_prodt_keyword::Column::ConsumeKeywordId"
    )]
    CommonConsumeProdtKeyword,
}

impl Related<super::spent_group_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpentGroupInfo.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::common_consume_prodt_keyword::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommonConsumeProdtKeyword.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
