//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "USERS")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub user_seq: i64,
    #[sea_orm(unique)]
    pub user_id: String,
    pub user_pw: String,
    pub user_pw_salt: String,
    pub user_name: String,
    pub user_birth: String,
    pub user_gender: Option<String>,
    pub main_oauth_channel: Option<String>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub created_by: String,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::spent_detail::Entity")]
    SpentDetail,
    #[sea_orm(has_many = "super::deposit_asset::Entity")]
    DepositAsset,
    #[sea_orm(has_many = "super::saving_asset::Entity")]
    SavingAsset,
    #[sea_orm(has_many = "super::earned_detail::Entity")]
    EarnedDetail,
    #[sea_orm(has_many = "super::telegram_room::Entity")]
    TelegramRoom,
    #[sea_orm(has_many = "super::user_payment_methods::Entity")]
    UserPaymentMethods,
    #[sea_orm(has_many = "super::users_email::Entity")]
    UsersEmail,
    #[sea_orm(has_many = "super::stock_asset::Entity")]
    StockAsset,
    #[sea_orm(has_many = "super::user_current_asset_snapshot::Entity")]
    UserCurrentAssetSnapshot,
    #[sea_orm(has_many = "super::crypto_asset::Entity")]
    CryptoAsset,
    #[sea_orm(has_many = "super::cash_asset::Entity")]
    CashAsset,
}

impl Related<super::spent_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpentDetail.def()
    }
}

impl Related<super::deposit_asset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DepositAsset.def()
    }
}

impl Related<super::saving_asset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavingAsset.def()
    }
}

impl Related<super::earned_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EarnedDetail.def()
    }
}

impl Related<super::telegram_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TelegramRoom.def()
    }
}

impl Related<super::user_payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPaymentMethods.def()
    }
}

impl Related<super::users_email::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersEmail.def()
    }
}

impl Related<super::stock_asset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockAsset.def()
    }
}

impl Related<super::user_current_asset_snapshot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCurrentAssetSnapshot.def()
    }
}

impl Related<super::crypto_asset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CryptoAsset.def()
    }
}

impl Related<super::cash_asset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CashAsset.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
