//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "USERS")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub user_seq: i64,
    #[sea_orm(unique)]
    pub user_id: String,
    pub user_pw: String,
    pub user_pw_salt: String,
    pub user_name: String,
    pub user_birth: String,
    pub user_gender: Option<String>,
    pub main_oauth_channel: Option<String>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub created_by: String,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::spent_detail::Entity")]
    SpentDetail,
    #[sea_orm(has_many = "super::telegram_room::Entity")]
    TelegramRoom,
    #[sea_orm(has_many = "super::user_payment_methods::Entity")]
    UserPaymentMethods,
}

impl Related<super::spent_detail::Entity> for Entity {
    /// Returns the relation definition to `SPENT_DETAIL`.
    fn to() -> RelationDef {
        Relation::SpentDetail.def()
    }
}

impl Related<super::telegram_room::Entity> for Entity {
    /// Returns the relation definition to `TELEGRAM_ROOM`.
    fn to() -> RelationDef {
        Relation::TelegramRoom.def()
    }
}

impl Related<super::user_payment_methods::Entity> for Entity {
    /// Returns the relation definition to `USER_PAYMENT_METHODS`.
    fn to() -> RelationDef {
        Relation::UserPaymentMethods.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
