//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "USER_PAYMENT_METHODS")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub payment_method_id: i64,
    pub payment_type_cd: String,
    pub payment_category_cd: String,
    pub card_id: String,
    pub card_alias: String,
    pub is_active: bool,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub created_by: String,
    pub updated_by: Option<String>,
    pub is_default: bool,
    pub user_seq: i64,
    pub card_company_nm: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserSeq",
        to = "super::users::Column::UserSeq"
    )]
    Users,
    #[sea_orm(has_many = "super::spent_detail::Entity")]
    SpentDetail,
}

impl Related<super::users::Entity> for Entity {
    /// Returns the relation definition to `USERS`.
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::spent_detail::Entity> for Entity {
    /// Returns the relation definition to `SPENT_DETAIL`.
    fn to() -> RelationDef {
        Relation::SpentDetail.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
